services:

db:
  image: mysql:8
  restart: always
  healthcheck:
    test:
      [
        "CMD-SHELL",
        "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD}",
      ]
    interval: 10s
    retries: 5
    start_period: 30s
    timeout: 10s
  volumes:
    - app-db-data:/var/lib/mysql
  env_file:
    - .env
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD?Variable not set}
    - MYSQL_DATABASE=${MYSQL_DATABASE?Variable not set}
    - MYSQL_USER=${MYSQL_USER?Variable not set}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD?Variable not set}
  ports:
    - "3306:3306"

  prestart:
    image: "${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}"
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
        restart: true
    command: bash scripts/prestart.sh
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
      - FRONTEND_HOST=${FRONTEND_HOST?Variable not set}
      - ENVIRONMENT=${ENVIRONMENT}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - SECRET_KEY=${SECRET_KEY?Variable not set}
      - FIRST_SUPERUSER=${FIRST_SUPERUSER?Variable not set}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD?Variable not set}
      - MYSQL_SERVER=db
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER?Variable not set}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD?Variable not set}

  backend:
    restart: "no"
    ports:
      - "8000:8000"
    build:
      context: ./backend
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
  frontend:
    restart: "no"
    ports:
      - "5173:80"
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8000
        - NODE_ENV=development
volumes:
  app-db-data:
